# English translations for Cabot-test package.
# Copyright (C) 2022 ORGANIZATION
# Automatically generated, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: Cabot-test 7\n"
"POT-Creation-Date: 2022-04-05 19:36+0900\n"
"PO-Revision-Date: 2022-04-05 10:17+0900\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: CaBot-odrive-diag.py:80 CaBot-odrive-diag.py:81
msgid "ODrivetool:not_found_find_any:"
msgstr "ODrive is not found by odrivetool."

#: CaBot-odrive-diag.py:85 CaBot-odrive-diag.py:87
msgid "ODrivetool:found_find_any:serial_no:"
msgstr "ODrive is connected. Serial No. : "

#: CaBot-odrive-diag.py:89 CaBot-odrive-diag.py:91
msgid "ODrivetool:have_err:NumOfErr:"
msgstr "An error was reported on ODrive. Number of errors: "

#: CaBot-odrive-diag.py:96 CaBot-odrive-diag.py:98
msgid "ODrivetool:TimeoutError:"
msgstr "ODrive is not found by odrivetool.(time out)"

#: CaBot-odrive-diag.py:102 CaBot-odrive-diag.py:104
msgid "ODrivetool:Exception:"
msgstr "An error occurred while searching for ODrive."
